apiVersion: v1
kind: Pod
metadata:
 name: calculator-pod
spec:
 nodeSelector:
  app: project
 containers:
  - name: cont1
    image: 429219761476.dkr.ecr.eu-north-1.amazonaws.com/calculator-java:1.0.35
 imagePullSecrets:
  - name: ecr-secret
    
